// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pingmessage.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingMessage struct {
	Pingnode             *uint64  `protobuf:"varint,1,req,name=pingnode" json:"pingnode,omitempty"`
	Timestamp            *int64   `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	AppliedIndex         *uint64  `protobuf:"varint,3,req,name=appliedIndex" json:"appliedIndex,omitempty"`
	FeatureBits          *uint64  `protobuf:"varint,4,opt,name=featureBits" json:"featureBits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_pingmessage_d172c36b23392fb4, []int{0}
}
func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (dst *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(dst, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetPingnode() uint64 {
	if m != nil && m.Pingnode != nil {
		return *m.Pingnode
	}
	return 0
}

func (m *PingMessage) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *PingMessage) GetAppliedIndex() uint64 {
	if m != nil && m.AppliedIndex != nil {
		return *m.AppliedIndex
	}
	return 0
}

func (m *PingMessage) GetFeatureBits() uint64 {
	if m != nil && m.FeatureBits != nil {
		return *m.FeatureBits
	}
	return 0
}

func init() {
	proto.RegisterType((*PingMessage)(nil), "protobuf.PingMessage")
}

func init() { proto.RegisterFile("pingmessage.proto", fileDescriptor_pingmessage_d172c36b23392fb4) }

var fileDescriptor_pingmessage_d172c36b23392fb4 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xc8, 0xcc, 0x4b,
	0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x53, 0x49, 0xa5, 0x69, 0x4a, 0xbd, 0x8c, 0x5c, 0xdc, 0x01, 0x99, 0x79, 0xe9, 0xbe, 0x10, 0x79,
	0x21, 0x29, 0x2e, 0x0e, 0x90, 0xf2, 0xbc, 0xfc, 0x94, 0x54, 0x09, 0x46, 0x05, 0x26, 0x0d, 0x96,
	0x20, 0x38, 0x5f, 0x48, 0x86, 0x8b, 0xb3, 0x24, 0x33, 0x37, 0xb5, 0xb8, 0x24, 0x31, 0xb7, 0x40,
	0x82, 0x49, 0x81, 0x49, 0x83, 0x39, 0x08, 0x21, 0x20, 0xa4, 0xc4, 0xc5, 0x93, 0x58, 0x50, 0x90,
	0x93, 0x99, 0x9a, 0xe2, 0x99, 0x97, 0x92, 0x5a, 0x21, 0xc1, 0x0c, 0xd6, 0x8d, 0x22, 0x26, 0xa4,
	0xc0, 0xc5, 0x9d, 0x96, 0x9a, 0x58, 0x52, 0x5a, 0x94, 0xea, 0x94, 0x59, 0x52, 0x2c, 0xc1, 0xa2,
	0xc0, 0xa8, 0xc1, 0x12, 0x84, 0x2c, 0x04, 0x08, 0x00, 0x00, 0xff, 0xff, 0x20, 0xbe, 0xea, 0x65,
	0xad, 0x00, 0x00, 0x00,
}
