// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pushrequest.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChangeRequest_ChangeRequestType int32

const (
	ChangeRequest_NEWREPO     ChangeRequest_ChangeRequestType = 1
	ChangeRequest_EDITREPO    ChangeRequest_ChangeRequestType = 2
	ChangeRequest_DELETEREPO  ChangeRequest_ChangeRequestType = 3
	ChangeRequest_PUSHREQUEST ChangeRequest_ChangeRequestType = 4
	ChangeRequest_PING        ChangeRequest_ChangeRequestType = 5
)

var ChangeRequest_ChangeRequestType_name = map[int32]string{
	1: "NEWREPO",
	2: "EDITREPO",
	3: "DELETEREPO",
	4: "PUSHREQUEST",
	5: "PING",
}
var ChangeRequest_ChangeRequestType_value = map[string]int32{
	"NEWREPO":     1,
	"EDITREPO":    2,
	"DELETEREPO":  3,
	"PUSHREQUEST": 4,
	"PING":        5,
}

func (x ChangeRequest_ChangeRequestType) Enum() *ChangeRequest_ChangeRequestType {
	p := new(ChangeRequest_ChangeRequestType)
	*p = x
	return p
}
func (x ChangeRequest_ChangeRequestType) String() string {
	return proto.EnumName(ChangeRequest_ChangeRequestType_name, int32(x))
}
func (x *ChangeRequest_ChangeRequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChangeRequest_ChangeRequestType_value, data, "ChangeRequest_ChangeRequestType")
	if err != nil {
		return err
	}
	*x = ChangeRequest_ChangeRequestType(value)
	return nil
}
func (ChangeRequest_ChangeRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pushrequest_276bf9b235a51807, []int{5, 0}
}

type UpdateRequest struct {
	Ref                  *string  `protobuf:"bytes,1,req,name=ref" json:"ref,omitempty"`
	From                 *string  `protobuf:"bytes,2,req,name=from" json:"from,omitempty"`
	To                   *string  `protobuf:"bytes,3,req,name=to" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pushrequest_276bf9b235a51807, []int{0}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetRef() string {
	if m != nil && m.Ref != nil {
		return *m.Ref
	}
	return ""
}

func (m *UpdateRequest) GetFrom() string {
	if m != nil && m.From != nil {
		return *m.From
	}
	return ""
}

func (m *UpdateRequest) GetTo() string {
	if m != nil && m.To != nil {
		return *m.To
	}
	return ""
}

type PushRequest struct {
	Pushnode             *uint64          `protobuf:"varint,1,req,name=pushnode" json:"pushnode,omitempty"`
	Pushtime             *int64           `protobuf:"varint,2,req,name=pushtime" json:"pushtime,omitempty"`
	Pushid               *int64           `protobuf:"varint,3,req,name=pushid" json:"pushid,omitempty"`
	Reponame             *string          `protobuf:"bytes,4,req,name=reponame" json:"reponame,omitempty"`
	Requests             []*UpdateRequest `protobuf:"bytes,5,rep,name=requests" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pushrequest_276bf9b235a51807, []int{1}
}
func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (dst *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(dst, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetPushnode() uint64 {
	if m != nil && m.Pushnode != nil {
		return *m.Pushnode
	}
	return 0
}

func (m *PushRequest) GetPushtime() int64 {
	if m != nil && m.Pushtime != nil {
		return *m.Pushtime
	}
	return 0
}

func (m *PushRequest) GetPushid() int64 {
	if m != nil && m.Pushid != nil {
		return *m.Pushid
	}
	return 0
}

func (m *PushRequest) GetReponame() string {
	if m != nil && m.Reponame != nil {
		return *m.Reponame
	}
	return ""
}

func (m *PushRequest) GetRequests() []*UpdateRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

type NewRepoRequest struct {
	Reponame             *string  `protobuf:"bytes,1,req,name=reponame" json:"reponame,omitempty"`
	Public               *bool    `protobuf:"varint,2,req,name=public" json:"public,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewRepoRequest) Reset()         { *m = NewRepoRequest{} }
func (m *NewRepoRequest) String() string { return proto.CompactTextString(m) }
func (*NewRepoRequest) ProtoMessage()    {}
func (*NewRepoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pushrequest_276bf9b235a51807, []int{2}
}
func (m *NewRepoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRepoRequest.Unmarshal(m, b)
}
func (m *NewRepoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRepoRequest.Marshal(b, m, deterministic)
}
func (dst *NewRepoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRepoRequest.Merge(dst, src)
}
func (m *NewRepoRequest) XXX_Size() int {
	return xxx_messageInfo_NewRepoRequest.Size(m)
}
func (m *NewRepoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRepoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewRepoRequest proto.InternalMessageInfo

func (m *NewRepoRequest) GetReponame() string {
	if m != nil && m.Reponame != nil {
		return *m.Reponame
	}
	return ""
}

func (m *NewRepoRequest) GetPublic() bool {
	if m != nil && m.Public != nil {
		return *m.Public
	}
	return false
}

type EditRepoRequest struct {
	Reponame             *string  `protobuf:"bytes,1,req,name=reponame" json:"reponame,omitempty"`
	Updaterequest        []byte   `protobuf:"bytes,2,req,name=updaterequest" json:"updaterequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditRepoRequest) Reset()         { *m = EditRepoRequest{} }
func (m *EditRepoRequest) String() string { return proto.CompactTextString(m) }
func (*EditRepoRequest) ProtoMessage()    {}
func (*EditRepoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pushrequest_276bf9b235a51807, []int{3}
}
func (m *EditRepoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditRepoRequest.Unmarshal(m, b)
}
func (m *EditRepoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditRepoRequest.Marshal(b, m, deterministic)
}
func (dst *EditRepoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditRepoRequest.Merge(dst, src)
}
func (m *EditRepoRequest) XXX_Size() int {
	return xxx_messageInfo_EditRepoRequest.Size(m)
}
func (m *EditRepoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditRepoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditRepoRequest proto.InternalMessageInfo

func (m *EditRepoRequest) GetReponame() string {
	if m != nil && m.Reponame != nil {
		return *m.Reponame
	}
	return ""
}

func (m *EditRepoRequest) GetUpdaterequest() []byte {
	if m != nil {
		return m.Updaterequest
	}
	return nil
}

type DeleteRepoRequest struct {
	Reponame             *string  `protobuf:"bytes,1,req,name=reponame" json:"reponame,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRepoRequest) Reset()         { *m = DeleteRepoRequest{} }
func (m *DeleteRepoRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRepoRequest) ProtoMessage()    {}
func (*DeleteRepoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pushrequest_276bf9b235a51807, []int{4}
}
func (m *DeleteRepoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRepoRequest.Unmarshal(m, b)
}
func (m *DeleteRepoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRepoRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRepoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRepoRequest.Merge(dst, src)
}
func (m *DeleteRepoRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRepoRequest.Size(m)
}
func (m *DeleteRepoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRepoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRepoRequest proto.InternalMessageInfo

func (m *DeleteRepoRequest) GetReponame() string {
	if m != nil && m.Reponame != nil {
		return *m.Reponame
	}
	return ""
}

type ChangeRequest struct {
	Ctype                *ChangeRequest_ChangeRequestType `protobuf:"varint,1,req,name=ctype,enum=protobuf.ChangeRequest_ChangeRequestType" json:"ctype,omitempty"`
	Newreporeq           *NewRepoRequest                  `protobuf:"bytes,2,opt,name=newreporeq" json:"newreporeq,omitempty"`
	Editreporeq          *EditRepoRequest                 `protobuf:"bytes,3,opt,name=editreporeq" json:"editreporeq,omitempty"`
	Deletereporeq        *DeleteRepoRequest               `protobuf:"bytes,4,opt,name=deletereporeq" json:"deletereporeq,omitempty"`
	Pushreq              *PushRequest                     `protobuf:"bytes,5,opt,name=pushreq" json:"pushreq,omitempty"`
	Pingmsg              *PingMessage                     `protobuf:"bytes,6,opt,name=pingmsg" json:"pingmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ChangeRequest) Reset()         { *m = ChangeRequest{} }
func (m *ChangeRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeRequest) ProtoMessage()    {}
func (*ChangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pushrequest_276bf9b235a51807, []int{5}
}
func (m *ChangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRequest.Unmarshal(m, b)
}
func (m *ChangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRequest.Marshal(b, m, deterministic)
}
func (dst *ChangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRequest.Merge(dst, src)
}
func (m *ChangeRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeRequest.Size(m)
}
func (m *ChangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRequest proto.InternalMessageInfo

func (m *ChangeRequest) GetCtype() ChangeRequest_ChangeRequestType {
	if m != nil && m.Ctype != nil {
		return *m.Ctype
	}
	return ChangeRequest_NEWREPO
}

func (m *ChangeRequest) GetNewreporeq() *NewRepoRequest {
	if m != nil {
		return m.Newreporeq
	}
	return nil
}

func (m *ChangeRequest) GetEditreporeq() *EditRepoRequest {
	if m != nil {
		return m.Editreporeq
	}
	return nil
}

func (m *ChangeRequest) GetDeletereporeq() *DeleteRepoRequest {
	if m != nil {
		return m.Deletereporeq
	}
	return nil
}

func (m *ChangeRequest) GetPushreq() *PushRequest {
	if m != nil {
		return m.Pushreq
	}
	return nil
}

func (m *ChangeRequest) GetPingmsg() *PingMessage {
	if m != nil {
		return m.Pingmsg
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateRequest)(nil), "protobuf.UpdateRequest")
	proto.RegisterType((*PushRequest)(nil), "protobuf.PushRequest")
	proto.RegisterType((*NewRepoRequest)(nil), "protobuf.NewRepoRequest")
	proto.RegisterType((*EditRepoRequest)(nil), "protobuf.EditRepoRequest")
	proto.RegisterType((*DeleteRepoRequest)(nil), "protobuf.DeleteRepoRequest")
	proto.RegisterType((*ChangeRequest)(nil), "protobuf.ChangeRequest")
	proto.RegisterEnum("protobuf.ChangeRequest_ChangeRequestType", ChangeRequest_ChangeRequestType_name, ChangeRequest_ChangeRequestType_value)
}

func init() { proto.RegisterFile("pushrequest.proto", fileDescriptor_pushrequest_276bf9b235a51807) }

var fileDescriptor_pushrequest_276bf9b235a51807 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0x3f, 0x69, 0xcd, 0xb8, 0x49, 0x93, 0x95, 0x80, 0xa5, 0x5c, 0x22, 0x8b, 0x43,
	0xb8, 0xa4, 0x52, 0xb8, 0x20, 0x71, 0x40, 0x88, 0xac, 0xa0, 0x12, 0x84, 0x30, 0x49, 0x84, 0x38,
	0xa6, 0xf5, 0xc4, 0xb1, 0xd4, 0xd8, 0xae, 0xbd, 0x56, 0xd5, 0x97, 0xe2, 0x35, 0x78, 0xad, 0xca,
	0xe3, 0xd8, 0x8e, 0x9b, 0x4b, 0x4f, 0xd9, 0x6f, 0x77, 0x7e, 0xdf, 0x7c, 0x3b, 0xf1, 0xc2, 0x20,
	0xc9, 0xb3, 0x6d, 0x4a, 0x77, 0x39, 0x65, 0x7a, 0x9c, 0xa4, 0xb1, 0x8e, 0x85, 0xc3, 0x3f, 0xd7,
	0xf9, 0xe6, 0x62, 0x90, 0x84, 0x51, 0xb0, 0xa3, 0x2c, 0x5b, 0x07, 0x54, 0x1e, 0x7a, 0x0a, 0xba,
	0xab, 0xc4, 0x5f, 0x6b, 0xc2, 0x92, 0x11, 0x7d, 0xb0, 0x52, 0xda, 0x48, 0x63, 0x68, 0x8e, 0x5e,
	0x60, 0xb1, 0x14, 0x02, 0xec, 0x4d, 0x1a, 0xef, 0xa4, 0xc9, 0x5b, 0xbc, 0x16, 0x3d, 0x30, 0x75,
	0x2c, 0x2d, 0xde, 0x31, 0x75, 0xec, 0xfd, 0x33, 0xc0, 0x9d, 0xe7, 0xd9, 0xb6, 0x72, 0xb9, 0x00,
	0xa7, 0x08, 0x12, 0xc5, 0x3e, 0xb1, 0x95, 0x8d, 0xb5, 0xae, 0xce, 0x74, 0xb8, 0x23, 0xf6, 0xb4,
	0xb0, 0xd6, 0xe2, 0x15, 0x9c, 0x14, 0xeb, 0xd0, 0x67, 0x6f, 0x0b, 0xf7, 0xaa, 0x60, 0x52, 0x4a,
	0xe2, 0x68, 0xbd, 0x23, 0x69, 0x73, 0xd7, 0x5a, 0x8b, 0x0f, 0xc5, 0x19, 0xb7, 0xcd, 0x64, 0x67,
	0x68, 0x8d, 0xdc, 0xc9, 0xeb, 0x71, 0x75, 0xe5, 0x71, 0xeb, 0x72, 0x58, 0x17, 0x7a, 0x53, 0xe8,
	0xcd, 0xe8, 0x1e, 0x29, 0x89, 0x0f, 0x22, 0xd7, 0x2d, 0x8c, 0x27, 0x2d, 0x38, 0xd6, 0xf5, 0x6d,
	0x78, 0xc3, 0x81, 0x1d, 0xdc, 0x2b, 0x6f, 0x01, 0xe7, 0xca, 0x0f, 0xf5, 0x73, 0x6d, 0xde, 0x41,
	0x37, 0xe7, 0x3c, 0xfb, 0x18, 0xec, 0x76, 0x86, 0xed, 0x4d, 0xef, 0x12, 0x06, 0x53, 0xba, 0xa5,
	0x22, 0xf5, 0xb3, 0x6c, 0xbd, 0xff, 0x16, 0x74, 0xbf, 0x6e, 0xd7, 0x51, 0x50, 0xff, 0x89, 0x9f,
	0xa1, 0x73, 0xa3, 0x1f, 0x92, 0xb2, 0xb4, 0x37, 0x79, 0xdf, 0xcc, 0xa3, 0x55, 0xd7, 0x56, 0xcb,
	0x87, 0x84, 0xb0, 0xe4, 0xc4, 0x47, 0x80, 0x88, 0xee, 0x8b, 0x0e, 0x29, 0xdd, 0x49, 0x73, 0x68,
	0x8c, 0xdc, 0x89, 0x6c, 0x5c, 0xda, 0xa3, 0xc3, 0x83, 0x5a, 0xf1, 0x09, 0x5c, 0xf2, 0x43, 0x5d,
	0xa1, 0x16, 0xa3, 0x6f, 0x1a, 0xf4, 0xc9, 0xbc, 0xf0, 0xb0, 0x5a, 0x7c, 0x81, 0xae, 0xcf, 0x57,
	0xaf, 0x70, 0x9b, 0xf1, 0xb7, 0x0d, 0x7e, 0x34, 0x19, 0x6c, 0x13, 0xe2, 0x12, 0x4e, 0xf7, 0x4f,
	0x40, 0x76, 0x18, 0x7e, 0xd9, 0xc0, 0x07, 0x5f, 0x28, 0x56, 0x55, 0x0c, 0x14, 0xcf, 0x22, 0x0b,
	0xe4, 0xc9, 0x11, 0x10, 0x46, 0xc1, 0xcf, 0xf2, 0xbd, 0x60, 0x55, 0xe5, 0xfd, 0x85, 0xc1, 0xd1,
	0xdc, 0x84, 0x0b, 0xa7, 0x33, 0xf5, 0x07, 0xd5, 0xfc, 0x57, 0xdf, 0x10, 0x67, 0xe0, 0xa8, 0xe9,
	0xd5, 0x92, 0x95, 0x29, 0x7a, 0x00, 0x53, 0xf5, 0x43, 0x2d, 0x15, 0x6b, 0x4b, 0x9c, 0x83, 0x3b,
	0x5f, 0x2d, 0xbe, 0xa3, 0xfa, 0xbd, 0x52, 0x8b, 0x65, 0xdf, 0x16, 0x0e, 0xd8, 0xf3, 0xab, 0xd9,
	0xb7, 0x7e, 0xe7, 0x31, 0x00, 0x00, 0xff, 0xff, 0x92, 0x34, 0xcc, 0xd8, 0xbe, 0x03, 0x00, 0x00,
}
