// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pushrequest.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	pushrequest.proto

It has these top-level messages:
	UpdateRequest
	PushRequest
	NewRepoRequest
	EditRepoRequest
	DeleteRepoRequest
	ChangeRequest
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChangeRequest_ChangeRequestType int32

const (
	ChangeRequest_NEWREPO     ChangeRequest_ChangeRequestType = 1
	ChangeRequest_EDITREPO    ChangeRequest_ChangeRequestType = 2
	ChangeRequest_DELETEREPO  ChangeRequest_ChangeRequestType = 3
	ChangeRequest_PUSHREQUEST ChangeRequest_ChangeRequestType = 4
)

var ChangeRequest_ChangeRequestType_name = map[int32]string{
	1: "NEWREPO",
	2: "EDITREPO",
	3: "DELETEREPO",
	4: "PUSHREQUEST",
}
var ChangeRequest_ChangeRequestType_value = map[string]int32{
	"NEWREPO":     1,
	"EDITREPO":    2,
	"DELETEREPO":  3,
	"PUSHREQUEST": 4,
}

func (x ChangeRequest_ChangeRequestType) Enum() *ChangeRequest_ChangeRequestType {
	p := new(ChangeRequest_ChangeRequestType)
	*p = x
	return p
}
func (x ChangeRequest_ChangeRequestType) String() string {
	return proto.EnumName(ChangeRequest_ChangeRequestType_name, int32(x))
}
func (x *ChangeRequest_ChangeRequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChangeRequest_ChangeRequestType_value, data, "ChangeRequest_ChangeRequestType")
	if err != nil {
		return err
	}
	*x = ChangeRequest_ChangeRequestType(value)
	return nil
}
func (ChangeRequest_ChangeRequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

type UpdateRequest struct {
	Ref              *string `protobuf:"bytes,1,req,name=ref" json:"ref,omitempty"`
	From             *string `protobuf:"bytes,2,req,name=from" json:"from,omitempty"`
	To               *string `protobuf:"bytes,3,req,name=to" json:"to,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpdateRequest) GetRef() string {
	if m != nil && m.Ref != nil {
		return *m.Ref
	}
	return ""
}

func (m *UpdateRequest) GetFrom() string {
	if m != nil && m.From != nil {
		return *m.From
	}
	return ""
}

func (m *UpdateRequest) GetTo() string {
	if m != nil && m.To != nil {
		return *m.To
	}
	return ""
}

type PushRequest struct {
	Pushnode         *uint64          `protobuf:"varint,1,req,name=pushnode" json:"pushnode,omitempty"`
	Pushtime         *int64           `protobuf:"varint,2,req,name=pushtime" json:"pushtime,omitempty"`
	Pushid           *int64           `protobuf:"varint,3,req,name=pushid" json:"pushid,omitempty"`
	Reponame         *string          `protobuf:"bytes,4,req,name=reponame" json:"reponame,omitempty"`
	Requests         []*UpdateRequest `protobuf:"bytes,5,rep,name=requests" json:"requests,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PushRequest) Reset()                    { *m = PushRequest{} }
func (m *PushRequest) String() string            { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()               {}
func (*PushRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PushRequest) GetPushnode() uint64 {
	if m != nil && m.Pushnode != nil {
		return *m.Pushnode
	}
	return 0
}

func (m *PushRequest) GetPushtime() int64 {
	if m != nil && m.Pushtime != nil {
		return *m.Pushtime
	}
	return 0
}

func (m *PushRequest) GetPushid() int64 {
	if m != nil && m.Pushid != nil {
		return *m.Pushid
	}
	return 0
}

func (m *PushRequest) GetReponame() string {
	if m != nil && m.Reponame != nil {
		return *m.Reponame
	}
	return ""
}

func (m *PushRequest) GetRequests() []*UpdateRequest {
	if m != nil {
		return m.Requests
	}
	return nil
}

type NewRepoRequest struct {
	Reponame         *string `protobuf:"bytes,1,req,name=reponame" json:"reponame,omitempty"`
	Public           *bool   `protobuf:"varint,2,req,name=public" json:"public,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NewRepoRequest) Reset()                    { *m = NewRepoRequest{} }
func (m *NewRepoRequest) String() string            { return proto.CompactTextString(m) }
func (*NewRepoRequest) ProtoMessage()               {}
func (*NewRepoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NewRepoRequest) GetReponame() string {
	if m != nil && m.Reponame != nil {
		return *m.Reponame
	}
	return ""
}

func (m *NewRepoRequest) GetPublic() bool {
	if m != nil && m.Public != nil {
		return *m.Public
	}
	return false
}

type EditRepoRequest struct {
	Reponame         *string `protobuf:"bytes,1,req,name=reponame" json:"reponame,omitempty"`
	Updaterequest    []byte  `protobuf:"bytes,2,req,name=updaterequest" json:"updaterequest,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EditRepoRequest) Reset()                    { *m = EditRepoRequest{} }
func (m *EditRepoRequest) String() string            { return proto.CompactTextString(m) }
func (*EditRepoRequest) ProtoMessage()               {}
func (*EditRepoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EditRepoRequest) GetReponame() string {
	if m != nil && m.Reponame != nil {
		return *m.Reponame
	}
	return ""
}

func (m *EditRepoRequest) GetUpdaterequest() []byte {
	if m != nil {
		return m.Updaterequest
	}
	return nil
}

type DeleteRepoRequest struct {
	Reponame         *string `protobuf:"bytes,1,req,name=reponame" json:"reponame,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteRepoRequest) Reset()                    { *m = DeleteRepoRequest{} }
func (m *DeleteRepoRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRepoRequest) ProtoMessage()               {}
func (*DeleteRepoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteRepoRequest) GetReponame() string {
	if m != nil && m.Reponame != nil {
		return *m.Reponame
	}
	return ""
}

type ChangeRequest struct {
	Ctype            *ChangeRequest_ChangeRequestType `protobuf:"varint,1,req,name=ctype,enum=protobuf.ChangeRequest_ChangeRequestType" json:"ctype,omitempty"`
	Newreporeq       *NewRepoRequest                  `protobuf:"bytes,2,opt,name=newreporeq" json:"newreporeq,omitempty"`
	Editreporeq      *EditRepoRequest                 `protobuf:"bytes,3,opt,name=editreporeq" json:"editreporeq,omitempty"`
	Deletereporeq    *DeleteRepoRequest               `protobuf:"bytes,4,opt,name=deletereporeq" json:"deletereporeq,omitempty"`
	Pushreq          *PushRequest                     `protobuf:"bytes,5,opt,name=pushreq" json:"pushreq,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *ChangeRequest) Reset()                    { *m = ChangeRequest{} }
func (m *ChangeRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeRequest) ProtoMessage()               {}
func (*ChangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ChangeRequest) GetCtype() ChangeRequest_ChangeRequestType {
	if m != nil && m.Ctype != nil {
		return *m.Ctype
	}
	return ChangeRequest_NEWREPO
}

func (m *ChangeRequest) GetNewreporeq() *NewRepoRequest {
	if m != nil {
		return m.Newreporeq
	}
	return nil
}

func (m *ChangeRequest) GetEditreporeq() *EditRepoRequest {
	if m != nil {
		return m.Editreporeq
	}
	return nil
}

func (m *ChangeRequest) GetDeletereporeq() *DeleteRepoRequest {
	if m != nil {
		return m.Deletereporeq
	}
	return nil
}

func (m *ChangeRequest) GetPushreq() *PushRequest {
	if m != nil {
		return m.Pushreq
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateRequest)(nil), "protobuf.UpdateRequest")
	proto.RegisterType((*PushRequest)(nil), "protobuf.PushRequest")
	proto.RegisterType((*NewRepoRequest)(nil), "protobuf.NewRepoRequest")
	proto.RegisterType((*EditRepoRequest)(nil), "protobuf.EditRepoRequest")
	proto.RegisterType((*DeleteRepoRequest)(nil), "protobuf.DeleteRepoRequest")
	proto.RegisterType((*ChangeRequest)(nil), "protobuf.ChangeRequest")
	proto.RegisterEnum("protobuf.ChangeRequest_ChangeRequestType", ChangeRequest_ChangeRequestType_name, ChangeRequest_ChangeRequestType_value)
}

func init() { proto.RegisterFile("pushrequest.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xbd, 0x0e, 0x0d, 0xe3, 0x26, 0x4d, 0x56, 0x02, 0x16, 0xb8, 0x44, 0x16, 0x87, 0x70,
	0x49, 0xa5, 0x70, 0x41, 0xe2, 0x80, 0x10, 0x59, 0x09, 0x24, 0xd4, 0x86, 0x49, 0x22, 0xce, 0x69,
	0x3d, 0x21, 0x96, 0x1a, 0xaf, 0x6b, 0xaf, 0x55, 0xf5, 0x1d, 0x78, 0x16, 0x9e, 0xb1, 0xf2, 0xc4,
	0xbf, 0xed, 0xa5, 0x27, 0xef, 0xb7, 0xfb, 0xfd, 0xed, 0x78, 0x61, 0x9c, 0xe4, 0xd9, 0x3e, 0xa5,
	0xdb, 0x9c, 0x32, 0x3b, 0x4b, 0x52, 0x63, 0x8d, 0xec, 0xf3, 0xe7, 0x2a, 0xdf, 0x05, 0x1a, 0x06,
	0x9b, 0x24, 0xdc, 0x5a, 0xc2, 0x23, 0x41, 0x8e, 0x40, 0xa4, 0xb4, 0x53, 0xce, 0xc4, 0x9d, 0xbe,
	0xc4, 0x62, 0x29, 0x25, 0x78, 0xbb, 0xd4, 0x1c, 0x94, 0xcb, 0x5b, 0xbc, 0x96, 0x43, 0x70, 0xad,
	0x51, 0x82, 0x77, 0x5c, 0x6b, 0x82, 0xff, 0x0e, 0xf8, 0xcb, 0x3c, 0xdb, 0x57, 0x2e, 0xef, 0xa0,
	0x5f, 0xa4, 0xc6, 0x26, 0x24, 0xb6, 0xf2, 0xb0, 0xc6, 0xd5, 0x99, 0x8d, 0x0e, 0xc4, 0x9e, 0x02,
	0x6b, 0x2c, 0x5f, 0xc3, 0x8b, 0x62, 0x1d, 0x85, 0xec, 0x2d, 0xb0, 0x44, 0x85, 0x26, 0xa5, 0xc4,
	0xc4, 0xdb, 0x03, 0x29, 0x8f, 0x53, 0x6b, 0x2c, 0x3f, 0x15, 0x67, 0x1c, 0x9b, 0xa9, 0xde, 0x44,
	0x4c, 0xfd, 0xf9, 0x9b, 0x59, 0x75, 0xbf, 0x59, 0xe7, 0x72, 0x58, 0x13, 0x83, 0x05, 0x0c, 0x2f,
	0xe8, 0x0e, 0x29, 0x31, 0xad, 0xca, 0x75, 0x84, 0xf3, 0x28, 0x82, 0x6b, 0x5d, 0xdd, 0x44, 0xd7,
	0x5c, 0xb8, 0x8f, 0x25, 0x0a, 0x56, 0x70, 0xa6, 0xc3, 0xc8, 0x3e, 0xd7, 0xe6, 0x03, 0x0c, 0x72,
	0xee, 0x53, 0xd6, 0x60, 0xb7, 0x53, 0xec, 0x6e, 0x06, 0xe7, 0x30, 0x5e, 0xd0, 0x0d, 0x15, 0xad,
	0x9f, 0x65, 0x1b, 0xfc, 0x13, 0x30, 0xf8, 0xbe, 0xdf, 0xc6, 0x7f, 0xeb, 0x9f, 0xf8, 0x15, 0x7a,
	0xd7, 0xf6, 0x3e, 0x39, 0x52, 0x87, 0xf3, 0x8f, 0xcd, 0x3c, 0x3a, 0xbc, 0x2e, 0x5a, 0xdf, 0x27,
	0x84, 0x47, 0x9d, 0xfc, 0x0c, 0x10, 0xd3, 0x5d, 0x91, 0x90, 0xd2, 0xad, 0x72, 0x27, 0xce, 0xd4,
	0x9f, 0xab, 0xc6, 0xa5, 0x3b, 0x3a, 0x6c, 0x71, 0xe5, 0x17, 0xf0, 0x29, 0x8c, 0x6c, 0x25, 0x15,
	0x2c, 0x7d, 0xdb, 0x48, 0x1f, 0xcd, 0x0b, 0xdb, 0x6c, 0xf9, 0x0d, 0x06, 0x21, 0x5f, 0xbd, 0x92,
	0x7b, 0x2c, 0x7f, 0xdf, 0xc8, 0x9f, 0x4c, 0x06, 0xbb, 0x0a, 0x79, 0x0e, 0x27, 0xe5, 0x7b, 0x57,
	0x3d, 0x16, 0xbf, 0x6a, 0xc4, 0xad, 0x17, 0x8a, 0x15, 0x2b, 0xb8, 0x84, 0xf1, 0x93, 0x31, 0x48,
	0x1f, 0x4e, 0x2e, 0xf4, 0x1f, 0xd4, 0xcb, 0xcb, 0x91, 0x23, 0x4f, 0xa1, 0xaf, 0x17, 0x3f, 0xd7,
	0x8c, 0x5c, 0x39, 0x04, 0x58, 0xe8, 0x5f, 0x7a, 0xad, 0x19, 0x0b, 0x79, 0x06, 0xfe, 0x72, 0xb3,
	0xfa, 0x81, 0xfa, 0xf7, 0x46, 0xaf, 0xd6, 0x23, 0xef, 0x21, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x67,
	0x95, 0x71, 0x70, 0x03, 0x00, 0x00,
}
